server:
  port: 3000
springdoc:
  #version: springdoc 라이브러리의 버전을 설정한다.
  version: '1.0.0'
  #api-docs: API 문서가 제공될 경로를 /api-docs로 설정한다.
  api-docs:
    path: /api-docs
  #요청 헤더 쪽의 컨텐트 타입
  default-consumes-media-type: application/json
  #응답 헤더 쪽의 컨텐트 타입
  default-produces-media-type: application/json
  #swagger-ui: Swagger UI의 외관 및 동작을 설정한다.
  swagger-ui:
    #operations-sorter : UI에서 작업을 알파벳 순서로 정렬한다.
    operations-sorter: alpha
    #tags-sorter: Swagger : UI에서 태그를 알파벳 순서로 정렬한다.
    tags-sorter: alpha
    #url 을 직접 확인 해 볼 수 있는 경로
    #path: Swagger UI에 액세스할 수 있는 경로를 /apidocs.html로 설정한다.
    path: /apidocs.html
    #disable-swagger-default-url: 기본 Swagger URL을 비활성화하고 명시적인 경로 /swagger-ui.html로만 접근하도록 한다.
    disable-swagger-default-url: true
    #doc-expansion: Swagger UI에서 문서 확장을 비활성화한다.
#    doc-expansion: none
  #paths-to-match: API 문서화에 포함할 경로 패턴을 설정한다. 여기서는 /api/** 로 시작하는 모든 경로가 문서화된다.
  paths-to-match:
    - /api/**