server:
  port: 3000

spring:
  #데이터 베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: ${db.username}
    password: ${db.password}

  #JPA 설정
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    #   dialect: org.hibernate.dialect.OracleDialect# 쿼리를 만들때 뭐로 만들지 모르는데 옛날 버전은 써줘야 함 근데 지금은 위에 oracledriver 있으니까 안써 도됨
    hibernate:
      ddlAuto: create #테이블을 변경한다. create 는 drop 하고 만든다

  #로거 설정
logging:
  level:
    org:
      hibernate:
        type:
          sql: trace